version: '3.8'

services:
  ozon-scraper:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./htmldata:/app/htmldata
      - ./json_data:/app/json_data
      - ./product_links.txt:/app/product_links.txt
      - ./used_links.txt:/app/used_links.txt
      - ./htmlParser/configUpdater/config.json:/app/htmlParser/configUpdater/config.json
      - ./htmlParser/configUpdater/template.html:/app/htmlParser/configUpdater/template.html
      - ./htmldata/html_config/config_html_file.html:/app/htmldata/html_config/config_html_file.html
      - ./run_update_config.py:/app/run_update_config.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
 