services:
  # browserless:
  #   image: browserless/chrome:latest  # Используем последнюю стабильную версию
  #   container_name: ozon_browserless
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PREBOOT_CHROME=true
  #     - DEFAULT_BLOCK_ADS=false
  #     - CONNECTION_TIMEOUT=600000
  #     - MAX_CONCURRENT_SESSIONS=1
  #     - ENABLE_CORS=true
  #     - DEFAULT_HEADLESS=true  # Используем boolean вместо строки
  #     - DEFAULT_IGNORE_HTTPS_ERRORS=true
  #     - DEFAULT_STEALTH=true
  #     - DEFAULT_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
  #   shm_size: '2gb'
  #   restart: unless-stopped

  ozon-scraper-api:
    build: .
    container_name: ozon_scraper_api
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - IS_DOCKER_ENV=true
    # - BROWSERLESS_URL=http://browserless:3000/webdriver
    # CHROME_BIN is now set in Dockerfile, no need to repeat unless overriding
    # - CHROME_BIN=/usr/bin/google-chrome
    # depends_on:
      # - browserless
    shm_size: '2gb'
    restart: unless-stopped