version: '3.11'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - IS_DOCKER_ENV=true
      # Раскомментируйте и укажите ваш прокси, если используете:
      # - HTTP_PROXY=http://user:password@host:port
      # - HTTPS_PROXY=http://user:password@host:port
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
 
  scraper:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./chrome-user-data:/home/scraper/.config/chrome
    shm_size: '2gb'
    ports:
      - "9222:9222"
    environment:
      - IS_DOCKER_ENV=true
      # Раскомментируйте и укажите ваш прокси, если используете:
      # - HTTP_PROXY=http://user:password@host:port
      # - HTTPS_PROXY=http://user:password@host:port
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
 